@global = http://localhost:3000

### Create User
POST {{global}}/users/ 
Content-Type: application/json

{
"name": {
"first": "Nev", "middle": "", "last": "Bd1"
}, "phone": "0512345567", "email": "25Admin@hotmail.com", "password": "Abc!123Abc", "image": {

"url": "", "alt": ""
}, "address": {

"state": "IL", "country": "Israel", "city": "Arad", "street": "Shoham", "houseNumber": 5, "zip": "2151510"
}, "isBusiness": true

}

### Login User

POST {{global}}/users/login 
Content-Type: application/json

{
    "email": "nick@gmail.com", "password": "Nick123456!"
}

//{
//"email": "25Admin@hotmail.com", "password": "Abc!123Abc"
//}

### Get All Users
GET {{global}}/users
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg1NjkzYmQyNjVjYTBlNmY2Yzc3ZmUiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY4NzI5OTB9.PDQ2H1W8KBsDny0PLQ3pDKCk1-SYR2NM_Bjk93u0xNc

### Get Specific User
GET {{global}}/users/6786936539eb6e6a73e84293 
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2OTM2NTM5ZWI2ZTZhNzNlODQyOTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2ODcyODMyfQ.HylVqfQJCKtHmXp70KVwIQxWMxrB9jlfvA-5ZWLXDoo
 
### Update User
PUT {{global}}/users/6786936539eb6e6a73e84293
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2OTM2NTM5ZWI2ZTZhNzNlODQyOTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2ODcyODMyfQ.HylVqfQJCKtHmXp70KVwIQxWMxrB9jlfvA-5ZWLXDoo

{
"name": {
"first": "Nev", "middle": "H.", "last": "Bd1"
}, "phone": "0512345567", "image": {

"url": "", "alt": ""
}, "address": {

"state": "IL", "country": "Israel", "city": "YAD-HaSHmonah", "street": "Shoham", "houseNumber": 5, "zip": "2151510"
}

}

### Partial Update User
PATCH {{global}}/users/6786936539eb6e6a73e84293
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2OTM2NTM5ZWI2ZTZhNzNlODQyOTMiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzM2ODcyODMyfQ.HylVqfQJCKtHmXp70KVwIQxWMxrB9jlfvA-5ZWLXDoo


{
"name": {
    "last": "UpdatedLastName" }
}
### Delete User
DELETE {{global}}/users/67864a5439eb6e6a73e84255
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg1NjkzYmQyNjVjYTBlNmY2Yzc3ZmUiLCJpc0J1c2luZXNzIjp0cnVlLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MzY4NzI5OTB9.PDQ2H1W8KBsDny0PLQ3pDKCk1-SYR2NM_Bjk93u0xNc


