const initialCards = [
  {
    title: "one",
    subtitle: "one two",
    description: "one two three",
    phone: 9725255110,
    email: "one@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 33,
      zip: "12",
    },
    bizNumber: 1000001,
    userId: "676844a3eaa5432d476822a5",
  },
  {
    title: "two",
    subtitle: "two two",
    description: "one two three",
    phone: 9725255114,
    email: "two@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 31,
      zip: "18",
    },
    bizNumber: 1000002,
    userId: "676844a3eaa5432d476822a5",
  },
  {
    title: "three",
    subtitle: "four five",
    description: "one two three",
    phone: 9725255119,
    email: "three@gmail.com",
    web: "https://www.google.com/",
    image: {
      url: "https://upload.wikimedia.org/wikipedia/en/e/ee/Front_%26_Back_Face_of_iPhone_16_Pro_Max.png",
      alt: "iphone",
    },
    address: {
      state: "",
      country: "USA",
      city: "LA",
      street: "LA city",
      houseNumber: 30,
      zip: "17",
    },
    bizNumber: 1000003,
    userId: "676844a3eaa5432d476822a5",
  },
];
module.exports = { initialCards };
